
DROP SCHEMA IF EXISTS FARM_HUB_DB;

CREATE SCHEMA FARM_HUB_DB;
USE FARM_HUB_DB;
CREATE TABLE user_login(
phone_number BIGINT(10)  PRIMARY KEY,
email_id VARCHAR(30) NOT NULL UNIQUE,
user_name VARCHAR(20) NOT NULL UNIQUE,
password VARCHAR(20) NOT NULL
);
INSERT INTO USER_LOGIN(PHONE_NUMBER,EMAIL_ID,USER_NAME,PASSWORD) VALUES(9063388012,"BHARATHREDDY@GMAIL.COM","BHARATH REDDY","REDDYS");
INSERT INTO USER_LOGIN(PHONE_NUMBER,EMAIL_ID,USER_NAME,PASSWORD) VALUES(9063388013,"BHARATH@GMAIL.COM","BHARATH","REDDYS");
INSERT INTO USER_LOGIN(PHONE_NUMBER,EMAIL_ID,USER_NAME,PASSWORD) VALUES(9063388014,"BHARATH13@GMAIL.COM","BHARATH1","REDDYS");


select  * from user_login;